// SPDX-License-Identifier: BUSL-1.1

// stem-openapi generates docs/openapi.yaml from the capability registry in
// internal/api (Server.routes), so the published API description cannot drift
// from the routes the daemon actually serves.
//
// Usage:
//
//	stem-openapi [-source docs/openapi-source.yaml] [-o docs/openapi.yaml]
//
// The registry supplies every path, its methods and its policy — auth, CSRF,
// rate limiting and the body cap. Prose and bodies come from the source file.
// The document itself is rendered by foundation's shared emitter; this command
// supplies only what is stem's: the registry, the source, the error envelope
// and the header.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/MustardSeedNetworks/foundation/pkg/httpserver/route"
	"github.com/MustardSeedNetworks/foundation/pkg/httpserver/route/openapi"

	"github.com/MustardSeedNetworks/stem/internal/api"
)

const header = "# GENERATED by `make openapi` (cmd/stem-openapi) — do not edit.\n" +
	"# Paths and their policy come from the capability registry\n" +
	"# (internal/api Server.routes); prose from docs/openapi-source.yaml.\n"

// outputFileMode is the generated document's permission bits.
const outputFileMode os.FileMode = 0o600

func main() {
	source := flag.String("source", "docs/openapi-source.yaml", "hand-written preamble and per-operation enrichment")
	out := flag.String("o", "", "output file path; '-' or empty writes to stdout")
	flag.Parse()

	if err := run(*source, *out); err != nil {
		fmt.Fprintf(os.Stderr, "stem-openapi: %v\n", err)
		os.Exit(1)
	}
}

func run(source, out string) error {
	sourceData, err := os.ReadFile(filepath.Clean(source))
	if err != nil {
		return err
	}
	doc, err := generate(sourceData, api.RouteManifest())
	if err != nil {
		return err
	}
	if out == "" || out == "-" {
		_, writeErr := os.Stdout.Write(doc)
		return writeErr
	}
	return writeOutput(out, doc)
}

// writeOutput writes doc to path through an [os.Root] on its directory, so the
// write cannot resolve outside the directory the operator named.
func writeOutput(path string, doc []byte) error {
	root, err := os.OpenRoot(filepath.Dir(path))
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()
	return root.WriteFile(filepath.Base(path), doc, outputFileMode)
}

// generate renders the OpenAPI document. Both inputs are explicit so the
// generator is testable without a file or a live server.
func generate(sourceData []byte, routes []route.Policy) ([]byte, error) {
	errSchema, err := errorSchema()
	if err != nil {
		return nil, err
	}
	return openapi.Generate(sourceData, routes, openapi.Options{
		Header:      header,
		ErrorSchema: errSchema,
	})
}
